spring:
  application:
    name: graphql
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://${app.database.host}/${app.database.db-name}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    url: jdbc:postgresql://${app.database.host}/${app.database.db-name}
    locations: classpath:db/migration
    user: ${app.database.username}
    password: ${app.database.password}
    baseline-on-migrate: true
    baseline-version: 0

app:
  database:
    username: root
    password: root
    host: localhost:5432
    db-name: graphql_db